apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
  namespace: default
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: my-container
      controlledResources:
      - memory
      - cpu
      maxAllowed:
        cpu: '2'
        memory: 2Gi
      minAllowed:
        cpu: 500m
        memory: 500Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  updatePolicy:
    updateMode: Auto
